# Generated by Django 5.2.15 on 2026-06-26 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courriers", "0003_search_vector_trigger"),
        ("utilisateurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DEPOT", "Dépôt"),
                            ("CONSULTATION", "Consultation"),
                            ("TELECHARGEMENT", "Téléchargement"),
                            ("MODIFICATION", "Modification"),
                            ("SUPPRESSION", "Suppression"),
                            ("CONNEXION", "Connexion"),
                            ("ADMIN", "Administration"),
                        ],
                        max_length=50,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
                (
                    "courrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courriers.courrier",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-horodatage"],
            },
        ),
    ]
