# Generated by Django 5.2.15 on 2026-06-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0002_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="echecs_connexion",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="verrouille_jusqu",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
