# Generated by Django 5.2.15 on 2026-06-26 11:45

import courriers.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Courrier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro doit être au format XXXXXX-AA (ex : 004901-26).",
                                regex="^\\d{6}-\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "type_courrier",
                    models.CharField(
                        choices=[("ENTRANT", "Entrant"), ("SORTANT", "Sortant")],
                        max_length=10,
                    ),
                ),
                ("date_courrier", models.DateField()),
                ("correspondant", models.CharField(max_length=200)),
                ("service_interne", models.CharField(blank=True, max_length=100)),
                ("signataire", models.CharField(blank=True, max_length=100)),
                ("objet", models.TextField(max_length=300)),
                ("annotations_directeur", models.TextField(blank=True)),
                ("observation", models.TextField(blank=True)),
                (
                    "fichier_pdf",
                    models.FileField(
                        max_length=500, upload_to=courriers.models.chemin_pdf
                    ),
                ),
                ("date_depot", models.DateTimeField(auto_now_add=True)),
                ("supprime", models.BooleanField(default=False)),
                (
                    "depose_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courriers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_courrier", "-date_depot"],
            },
        ),
    ]
