# Generated by Django 5.2.15 on 2026-06-26 12:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courriers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courrier",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="courrier",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="courriers_c_search__f61bde_gin"
            ),
        ),
    ]
